-- GENERATED by theme/render.sh from theme/palette.sh — do not edit.

local M = {
    bg         = "0e1215",
    fg         = "e6e9ef",
    fg_dim     = "9aa3ad",
    glass      = "ffffff",

    accent     = "8fd6b5",
    accent_alt = "7fb8e6",
    red        = "ef7a7a",
    orange     = "f0a46c",
    yellow     = "e9cf7a",
    green      = "a3d98f",
    blue       = "7fb8e6",
    purple     = "c3a3e6",
    cyan       = "7fd6d2",

    bg_alpha      = 0.45,
    overlay_alpha = 0.85,
    surface_alpha = 0.07,
    hover_alpha   = 0.14,
    border_alpha  = 0.12,
    shadow_alpha  = 0.35,

    win_opacity_active   = 0.96,
    win_opacity_inactive = 0.88,
}

-- Hyprland color string, e.g. M.rgba(M.accent, 0.9) -> "rgba(8fd6b5e6)"
function M.rgba(hex, alpha)
    return string.format("rgba(%s%02x)", hex, math.floor((alpha or 1) * 255 + 0.5))
end

return M
